<?xml version="1.0"?>
<package format="3">
  <name>rm_interfaces</name>
  <version>0.1.0</version>
  <description>自瞄自定义消息（独立接口包，标准姿势）</description>
  <maintainer email="yq@example.com">yq</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>

  <exec_depend>rosidl_default_runtime</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
